In [281]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [282]:
df=pd.read_csv("train.csv")
df.head(3)

PassengerId  Survived  Pclass   
0            1         0       3  \
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp   
0                            Braund, Mr. Owen Harris    male  22.0      1  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [283]:
df.drop(columns=["PassengerId","Name","Ticket","Cabin"],inplace=True)

In [284]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [285]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [286]:
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=["Survived"]),df["Survived"],test_size=0.2,random_state=42)

In [287]:
x_train

Pclass     Sex   Age  SibSp  Parch      Fare Embarked
331       1    male  45.5      0      0   28.5000        S
733       2    male  23.0      0      0   13.0000        S
382       3    male  32.0      0      0    7.9250        S
704       3    male  26.0      1      0    7.8542        S
813       3  female   6.0      4      2   31.2750        S
..      ...     ...   ...    ...    ...       ...      ...
106       3  female  21.0      0      0    7.6500        S
270       1    male   NaN      0      0   31.0000        S
860       3    male  41.0      2      0   14.1083        S
435       1  female  14.0      1      2  120.0000        S
102       1    male  21.0      0      1   77.2875        S

[712 rows x 7 columns]

In [288]:
y_train.head()

331    0
733    0
382    0
704    0
813    0
Name: Survived, dtype: int64

In [289]:
#apply imputer
si_age=SimpleImputer()
si_embarked=SimpleImputer(strategy="most_frequent")

In [290]:
x_train_age=si_age.fit_transform(x_train[["Age"]])
x_train_age.shape

(712, 1)

In [291]:
x_train_embarked=si_embarked.fit_transform(x_train[["Embarked"]])
x_train_embarked.shape

(712, 1)

In [292]:
x_test_age=si_age.fit_transform(x_test[["Age"]])
x_test_age.shape

(179, 1)

In [293]:
x_test_embarked=si_embarked.fit_transform(x_test[["Embarked"]])
x_test_embarked.shape

(179, 1)

In [294]:
#one hot encoding
ohe_sex=OneHotEncoder(sparse_output=False,handle_unknown="ignore")
ohe_embarked=OneHotEncoder(sparse_output=False,handle_unknown="ignore")

In [295]:
x_train_sex=ohe_sex.fit_transform(x_train[["Sex"]])
x_train_sex.shape

(712, 2)

In [296]:
x_train_embarked=ohe_embarked.fit_transform(x_train_embarked)
x_train_embarked.shape

(712, 3)

In [297]:
x_test_sex=ohe_sex.fit_transform(x_test[["Sex"]])
x_test_sex.shape

(179, 2)

In [298]:
x_test_oheembarked=ohe_embarked.fit_transform(x_test_embarked)
x_test_oheembarked.shape

(179, 3)

In [299]:
#names=ohe_embarked.get_feature_names_out(input_features=x_train[["Embarked"]].columns)

In [300]:
#x_test_oheembarked=pd.DataFrame(x_test_oheembarked,columns=names)

In [301]:
x_train_rem=x_train.drop(columns=["Age","Sex","Embarked"])
x_train_rem

Pclass  SibSp  Parch      Fare
331       1      0      0   28.5000
733       2      0      0   13.0000
382       3      0      0    7.9250
704       3      1      0    7.8542
813       3      4      2   31.2750
..      ...    ...    ...       ...
106       3      0      0    7.6500
270       1      0      0   31.0000
860       3      2      0   14.1083
435       1      1      2  120.0000
102       1      0      1   77.2875

[712 rows x 4 columns]

In [302]:
x_test_rem=x_test.drop(columns=["Age","Sex","Embarked"])
x_test_rem

Pclass  SibSp  Parch     Fare
709       3      1      1  15.2458
439       2      0      0  10.5000
840       3      0      0   7.9250
720       2      0      1  33.0000
39        3      1      0  11.2417
..      ...    ...    ...      ...
433       3      0      0   7.1250
773       3      0      0   7.2250
25        3      1      5  31.3875
84        2      0      0  10.5000
10        3      1      1  16.7000

[179 rows x 4 columns]

In [303]:
x_train_transformed=np.concatenate((x_train_rem,x_train_age,x_train_sex,x_train_embarked),axis=1)
x_train_transformed

array([[1., 0., 0., ..., 0., 0., 1.],
       [2., 0., 0., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 0., 1.],
       ...,
       [3., 2., 0., ..., 0., 0., 1.],
       [1., 1., 2., ..., 0., 0., 1.],
       [1., 0., 1., ..., 0., 0., 1.]])

In [304]:
x_train_oheembarked.ndim

2

In [305]:
x_test_transformed=np.concatenate((x_test_rem,x_test_age,x_test_ohesex,x_test_oheembarked),axis=1)
x_test_transformed

array([[3., 1., 1., ..., 1., 0., 0.],
       [2., 0., 0., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 0., 1.],
       ...,
       [3., 1., 5., ..., 0., 0., 1.],
       [2., 0., 0., ..., 0., 0., 1.],
       [3., 1., 1., ..., 0., 0., 1.]])

In [306]:
clf=DecisionTreeClassifier()

In [307]:
clf.fit(x_train_transformed,y_train)

DecisionTreeClassifier()

In [308]:
y_pred=clf.predict(x_test_transformed)

In [309]:
y_pred

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1], dtype=int64)

In [310]:
from sklearn.metrics import accuracy_score

In [311]:
accuracy_score(y_test,y_pred)

0.7597765363128491

In [312]:
import pickle

In [313]:
pickle.dump(ohe_sex,open('ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open('ohe_embarked.pkl','wb'))
pickle.dump(clf,open('clf.pkl','wb'))

In [314]:
#predict
import pickle
import numpy as np
ohe_sex=pickle.load(open('ohe_sex.pkl','rb'))
ohe_embarked=pickle.load(open('ohe_embarked.pkl','rb'))
clf=pickle.load(open('clf.pkl','rb'))

In [345]:
#assume user input
test_input=np.array([1,'female',38.0,1,0,71.2833,'C'],dtype=object).reshape(1,7)
test_input

array([[1, 'female', 38.0, 1, 0, 71.2833, 'C']], dtype=object)

In [346]:
test_input_sex=ohe_sex.transform(test_input[:,1].reshape(1,1))
test_input_sex

C:\Users\nikie\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0.]])

In [347]:
test_input_embarked=ohe_embarked.transform(test_input[:,6].reshape(1,1))
test_input_embarked

array([[1., 0., 0.]])

In [348]:
test_input_age=test_input[:,2].reshape(1,1)

In [349]:
test_input_transformed=np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [350]:
test_input_transformed.shape

(1, 10)

In [351]:
clf.predict(test_input_transformed)

array([1], dtype=int64)

*input2

In [352]:
test_input=np.array([3,'male',35.0,0,0,8.0500,'S'],dtype=object).reshape(1,7)
test_input

array([[3, 'male', 35.0, 0, 0, 8.05, 'S']], dtype=object)

In [353]:
test_input_sex=ohe_sex.transform(test_input[:,1].reshape(1,1))
test_input_sex

C:\Users\nikie\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 1.]])

In [354]:
test_input_embarked=ohe_embarked.transform(test_input[:,6].reshape(1,1))
test_input_embarked

array([[0., 0., 1.]])

In [355]:
test_input_age=test_input[:,2].reshape(1,1)

In [356]:
test_input_transformed=np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [357]:
clf.predict(test_input_transformed)

array([0], dtype=int64)